name: Docker Publish

on:
  # When changes are pushed to the "main" branch, run it
  push:
    branches:
      - main

  # Run every day at 1200 UTC to update the images
  schedule:
    - cron: '0 12 * * *'

jobs:
  push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag image
        run: docker build ssh/. --tag serversideup/docker-ssh

      - name: Push version image to DockerHub
        run: docker push serversideup/docker-ssh